### PR TITLE
Add typescript

### PR DESCRIPTION
**Pull request by riverrun-git**
This has been tested successfully with a minimal project, not a complete plugin.
Both 'import' and 'require' worked depending on the project setup.
The generated client.d.ts file is rubbish, as all the types are 'any'.
This can be fixed with JSDoc comments in a next step.
Any issues, please let me know.

To generate the files run 'npm run build' (or just tsc).
The files to package for npm are then in the dist folder

### CODE REVIEW

**Review by spdermn02 — DISMISSED** [review]
Changes seem reasonable.

**Comment by spdermn02** [comment]
i published as tag `alpha-ts` out to npmjs.org - but it seems like only the dist/index.js got published - seems to be something I'm misunderstanding about the process - i'll have to do more digging later

**Comment by riverrun-git** [comment]
I didn't want to publish to npmjs.org, but I might have a go to see what's involved.

**Comment by riverrun-git** [comment]
Right. Without having to publish myself, I found out this:
The issue is that `npm publish` won't publish anything ignored in `.gitignore`
The solution is to add a `.npmignore` file telling npm not to ignore files in `dist` when publishing.
I have added that file to the pull request.
You can run `npm pack` and look at the resulting file to check that the correct files will be published.

**Comment by spdermn02** [comment]
perfect - thank you! my test now executes with no issue it seems

**Comment by spdermn02** [comment]
interesting - the only other thing that i now notice, is that the unless import like this  `import TP from 'touchportal-api/dist/src'` the typings aren't used, but maybe that's another thing I don't know abotu the TS process and build that needs to be handled differently.  so my TouchPortal-Dynamic-Icons plugin was my first jump into TS and that's what I'm testing this implementation in. I feel like I'm doing something incorrect.

**Comment by spdermn02** [comment]
okay - i did add to the package.json a files declaration and only publish the `dist/**/*` files
and then in my import `import TP from 'touchportal-api/'` kicked off the use of the TS based types. so maybe the solution is just that extra `/` in the import - seems odd though

**Comment by spdermn02** [comment]
okay figured that out - it was due to a declarations.ts i had in my project from the beginning. it seems to be functioning as expected now.

**Review by spdermn02 — APPROVED** [review]

**Pull request merged**
